<?php

$METs = array(
	array("hodanje, 5 km/h, umjereni intenzitet", 3),
	array("trčanje, 8 km/h, umjereni intenzitet", 8.3),
	array("vožnja bicikla <16 km/h", 4),
	array("istezanje, blago", 2.3),
	array("tuširanje, stojeći", 2),
	array("aerobik u vodi", 5.5),
	array("aerobik, umjereni intenzitet", 5),
	array("aerobik, visoki intenzitet", 7.3),
	array("alpinizam, umjereni intenzitet", 5.8),
	array("alpinizam, visoki intenzitet", 8),
	array("atletske discipline: bacanje diska, kugle, kladiva", 4),
	array("atletske discipline: skok u vis, skok u dalj, skok s motkom, bacanje koplja", 6),
	array("badminton, umjereni intenzitet", 5.5),
	array("badminton, visoki intenzitet", 7),
	array("biljar", 2.5),
	array("boćanje", 3.3),
	array("bojanje ograde", 4.5),
	array("bojanje zidova", 3.3),
	array("boks, natjecateljski", 12.8),
	array("boks, sparing", 7.8),
	array("boks, trening s vrećom", 5.5),
	array("borilačke vještine, umjereni intenzitet, početnici", 5.3),
	array("borilačke vještine, visoki intenzitet", 10.3),
	array("briga za malo dijete", 2.5),
	array("brisanje prašine", 2.3),
	array("cijepanje drveta", 6.3),
	array("čišćenje (glačanje, mijenjanje posteljine)", 2.5),
	array("čišćenje (pranje prozora, automobila, čišćenje garaže), umjereni intenzitet", 3.5),
	array("čišćenje snijega lopatom", 6),
	array("čišćenje, metenje", 3.3),
	array("čitanje", 1.3),
	array("čupanje korova", 3.5),
	array("curling", 4),
	array("dirigiranje", 2.3),
	array("dodavanje loptom", 2.5),
	array("dojenje", 2),
	array("drvodjelstvo", 3),
	array("električarski poslovi", 3.3),
	array("frizbi, rekreativno, niski intenzitet", 3),
	array("frizbi, ultimate flying disc, natjecateljski", 8),
	array("gimnastika, niski intenzitet", 3.8),
	array("gledanje televizije", 1),
	array("golf", 4.8),
	array("grabljanje lišća", 3.8),
	array("graničar", 5.8),
	array("guranje automobila", 6),
	array("guranje dječjih kolica", 4),
	array("hodanje, 3 km/h, vrlo niski intenzitet", 2),
	array("hodanje, 4 km/h, niski intenzitet", 2.8),
	array("hodanje, 5 km/h, uzbrdo", 5.3),
	array("hodanje, 6 km/h, visoki intenzitet", 4.3),
	array("hodanje, 7 km/h, visoki intenzitet", 5),
	array("hodanje, brzo hodanje, natjecateljski", 6.5),
	array("hodanje, niski intenzitet", 2),
	array("hodanje, srednji intenzitet", 3.5),
	array("hodanje, visoki intenzitet", 4.3),
	array("hokej na ledu", 8),
	array("hokej na ledu, natjecateljski", 10),
	array("hokej na travi", 7.8),
	array("hrvanje", 6),
	array("igra s djecom, sjedeći, niski intenzitet", 2.2),
	array("igra s djecom, stojeći, niski intenzitet", 2.8),
	array("igra s kućnim ljubimcima, hodajući, umjereni intenzitet", 4),
	array("igra s kućnim ljubimcima, hodajući, visoki intenzitet", 5),
	array("igra s kućnim ljubimcima, sjedeći", 2.8),
	array("igranje društvenih igara", 1.5),
	array("igranje šaha", 1.5),
	array("igranje video igara", 1),
	array("jedrenje na dasci, niski intenzitet", 5),
	array("jedrenje na dasci, visoki intenzitet", 11),
	array("jedrenje, niski intenzitet", 3),
	array("jedrenje, srednji intenzitet", 4.5),
	array("kampiranje", 2.5),
	array("kartanje", 1.5),
	array("klizanje, natjecateljski, vrlo visoki intenzitet", 14),
	array("klizanje, niski intenzitet", 5.5),
	array("klizanje, umjereni intenzitet", 7),
	array("klizanje, visoki intenzitet", 9),
	array("konjički sportovi, niski intenzitet", 3.8),
	array("konjički sportovi, umjereni intenzitet", 5.8),
	array("konjički sportovi, visoki intenzitet", 7.3),
	array("konjički sportovi, vrlo visoki intenzitet", 9),
	array("konzumiranje hrane, sjedeći", 1.5),
	array("kopanje lopatom", 8),
	array("korištenje teških strojeva", 6.3),
	array("košarka u kolicima, wheelchair basketball", 7.8),
	array("košarka, gađanje koša, niski intenzitet", 4.5),
	array("košarka, natjecateljski, visoki intenzitet", 8),
	array("košarka, umjereni intenzitet", 6.5),
	array("košnja trave", 5.5),
	array("kružni trening s utezima, visoki intenzitet", 8),
	array("kružni trening, umjereni intenzitet", 4.3),
	array("kućanski popravci, niski intenzitet", 2.5),
	array("kućanski popravci, umjereni intenzitet", 4.5),
	array("kućanski popravci, visoki intenzitet", 6),
	array("kuglanje", 3),
	array("kuharski poslovi", 2.5),
	array("kuhinjske aktivnosti: kuhanje, pranje suđa", 3.3),
	array("kupanje psa", 3.5),
	array("kupovina namirnica", 2.5),
	array("mačevanje", 6),
	array("mišićni trening (čučnjevi, podizanje utega), umjereni intenzitet", 5),
	array("mišićni trening (podizanje utega, body building), visoki intenzitet", 6),
	array("mišićni trening (sklekovi, trbušnjaci, zgibovi, vježbe za leđa), umjereni intenzitet", 3.8),
	array("mišićni trening (trbušnjaci), niski intenzitet", 2.8),
	array("moto-cross", 4),
	array("njega o starijoj osobi ili osobi s invaliditetom", 4),
	array("nogomet, natjecateljski", 10),
	array("nogomet, rekreativno", 7),
	array("nordijsko hodanje, 5 km/h, umjereni intenzitet", 4.8),
	array("nordijsko hodanje, 8 km/h, visoki intenzitet", 9.5),
	array("nošenje malog djeteta, lakšeg od 7 kg", 3),
	array("nošenje namirnica po stubama", 7.5),
	array("nošenje namještaja po stubištu", 9),
	array("odbojka", 4),
	array("odbojka na pijesku", 8),
	array("odbojka, natjecateljski", 6),
	array("orijentacijsko trčanje", 9),
	array("pikado", 2.5),
	array("pilates, umjereni intenzitet", 3),
	array("piljenje drveta", 5.5),
	array("pisanje", 1.3),
	array("planinarenje", 6),
	array("ples u noćnom klubu, visoki intenzitet", 7.8),
	array("ples, balet ili moderni ples, umjereni intenzitet", 5),
	array("ples, balet ili moderni ples, visoki intenzitet", 6.8),
	array("ples, standardni ili latino, brzim tempom", 5.5),
	array("ples, standardni ili latino, niski intenzitet", 3),
	array("ples, standardni, natjecateljski", 11.3),
	array("plesanje, folklorno, umjereni intenzitet", 4.5),
	array("plivanje kraul, umjereni intenzitet", 5.8),
	array("plivanje kraul, visoki intenzitet", 9.8),
	array("plivanje leđnim stilom, umjereni intenzitet", 4.8),
	array("plivanje leđnim stilom, visoki intenzitet", 9.5),
	array("plivanje leptir stilom, umjereni intenzitet", 6),
	array("plivanje leptir stilom, visoki intenzitet", 13.8),
	array("plivanje prsnim stilom, umjereni intenzitet", 5.3),
	array("plivanje prsnim stilom, visoki intenzitet", 10.3),
	array("popravak automobila", 3.3),
	array("poslovi čistača", 3.8),
	array("poslovi drvosječe", 8),
	array("poslovi frizera", 1.8),
	array("poslovi knjižničara", 2.3),
	array("poslovi pekara", 4),
	array("poslovi ribara, umjereni intenzitet", 5),
	array("poslovi ribara, visoki intenzitet", 7),
	array("poslovi sobara", 4),
	array("poslovi sportskog trenera, povremeno aktivno", 4),
	array("poslovi vatrogasca", 8),
	array("poslovi vodoinstalatera", 3),
	array("pospremanje sobe", 4.8),
	array("postavljanje krova, postavljanje ograde", 6),
	array("postavljanje pločica, laminata ili parketa", 3.8),
	array("postavljanje tepiha", 4.5),
	array("pranje podova", 4.5),
	array("pranje ruku, zubi, šminkanje", 2),
	array("premještanje namještaja, nošenje kutija", 5.8),
	array("preskakanje vijače, 100-120 u minuti, umjereni intenzitet", 11.8),
	array("preskakanje vijače, 120-160 u minuti, visoki intenzitet", 12.3),
	array("preskakanje vijače, do 100 u minuti, niski intenzitet", 8.8),
	array("pričanje, sjedeći", 1.5),
	array("pričanje, stojeći", 1.8),
	array("ribanje poda, kade i kupaonice", 3.5),
	array("ribolov, sjedeći", 2.5),
	array("rolanje, in-line skating, 14 km/h , niski intenzitet", 7.5),
	array("rolanje, in-line skating, 18 km/h, umjereni intenzitet", 9.8),
	array("rolanje, in-line skating, 22  km/h, visoki intenzitet", 12.3),
	array("rugby", 6.3),
	array("rugby, natjecateljski", 8.3),
	array("rukomet, natjecateljski, visoki intenzitet", 12),
	array("rukomet, rekreativno, umjereni intenzitet", 8),
	array("seksualna aktivnost, ljubljenje, niski intenzitet", 1.3),
	array("seksualna aktivnost, umjereni intenzitet", 1.8),
	array("seksualna aktivnost, visoki intenzitet", 2.8),
	array("šetnja i lagano trčanje s djecom", 3.5),
	array("šetnja i trčanje s djecom, visoki intenzitet", 5.8),
	array("šetnja s kućnim ljubimcima", 3),
	array("sinkronizirano plivanje", 8),
	array("šivanje šivaćim strojem", 2.8),
	array("šivanje, krojenje, zamatanje poklona", 1.3),
	array("sjedenje", 1.3),
	array("sjedenje na frizuri ili manikuri", 1.3),
	array("sjedenje u publici na sportskom događaju", 1.5),
	array("skakanje na trampolinu", 3.5),
	array("skateboarding, natjecateljski, visoki intenzitet", 6),
	array("skateboarding, umjereni intenzitet", 5),
	array("skijanje, natjecateljski, vrlo visoki intenzitet", 12.5),
	array("skijanje, snowboarding, niski intenzitet", 4.3),
	array("skijanje, umjereni intenzitet", 7),
	array("skijanje, visoki intenzitet", 8),
	array("skokovi u vodu", 3),
	array("skvoš, umjereni intenzitet", 7.3),
	array("skvoš, visoki intenzitet", 12),
	array("slaganje kreveta, mijenjanje posteljine", 3.3),
	array("slikanje, stojeći", 1.8),
	array("smijanje, sjedeći", 1),
	array("sobni bicikl, 101-160 watta, visoki intenzitet", 8.8),
	array("sobni bicikl, 161-200 watta, visoki intenzitet", 11),
	array("sobni bicikl, 201-270 watta, vrlo visoki intenzitet", 14),
	array("sobni bicikl, 30 do 50 watta, niski intenzitet", 3.5),
	array("sobni bicikl, 51-89 watta, niski do umjereni intenzitet", 4.8),
	array("sobni bicikl, 90 do 100 watta, umjereni intenzitet", 6.8),
	array("softball ili baseball, umjereni intenzitet", 5),
	array("spavanje", 0.9),
	array("stajanje, čekanje u redu", 1.3),
	array("stolni tenis, umjereni intenzitet", 4),
	array("streličarstvo", 4.3),
	array("sviranje bubnjeva", 3.8),
	array("sviranje flaute", 2),
	array("sviranje gitare, klasična glazba", 2),
	array("sviranje gitare, rock and roll", 3),
	array("sviranje glazbenog instrumenta", 2),
	array("sviranje klavira", 2.3),
	array("sviranje orgulja", 2),
	array("sviranje trube", 1.8),
	array("sviranje violine", 2.5),
	array("sviranje violončela", 2.3),
	array("tenis", 7.3),
	array("tenis, parovi", 6),
	array("tipkanje na tipkovnici", 1.3),
	array("trčanje po stubištu uzbrdo", 15),
	array("trčanje, 11 km/h, visoki intenzitet", 11),
	array("trčanje, 14 km/h, vrlo visoki intenzitet", 12.8),
	array("trčanje, 20 km/h, vrlo visoki intenzitet, natjecateljski", 19.8),
	array("trčanje, 6 km/h, niski intenzitet", 6),
	array("trčanje, cross country", 9),
	array("trčanje, maraton", 13.3),
	array("usisavanje", 3.3),
	array("uspinjanje po ljestvama", 8),
	array("uspinjanje po stubištu, niski intenzitet", 4),
	array("uspinjanje po stubištu, visoki intenzitet", 8.8),
	array("vaterpolo", 10),
	array("veslački ergometar, 100 watta, umjereni intenzitet", 7),
	array("veslački ergometar, 150 watta, visoki intenzitet", 8.5),
	array("veslački ergometar, 200 watta, vrlo visoki intenzitet", 12),
	array("veslački ergometar, niski intenzitet", 4.8),
	array("veslanje, niski intenzitet", 2.8),
	array("veslanje, umjereni intenzitet", 5.8),
	array("veslanje, visoki intenzitet", 12.5),
	array("vješanje rublja, pražnjenje perilice rublja, pakiranje kofera", 2.5),
	array("vožnja automobila, vozač", 2.5),
	array("vožnja bicikla >32 km/h, natjecateljski", 15.8),
	array("vožnja bicikla 16 km/h",	5.8),
	array("vožnja bicikla 22 km/h", 10.0),
	array("vožnja bicikla uzbrdo, natjecateljski", 16.0),
	array("vožnja bicikla uzbrdo, visoki intenzitet", 14.0),
	array("vožnja motocikla", 3.5),
	array("vrtlarenje",	4.0),
	array("vrtlarenje, berba voća i povrća", 3.5),
	array("vrtlarenje, okopavanje vrta", 3.5),
	array("vrtlarenje, sadnja cvijeća", 2.0),
	array("vrtlarenje, sadnja drveća", 4.5),
	array("vrtlarenje, zalijevanje biljaka", 2.5),
	array("vrtlarenje, zalijevanje biljaka hodajući", 3.0),
	array("yoga", 3.3),
	array("zabijanje čavala", 3.0),
	array("žongliranje", 4.0)
);

?>